# -*- Makefile -*-

SHELL = bash

# man openssl-req, openssl-x509 for references
# subj[ req_distinguished_name ] "/C/ST/L/O/OU/CN/emailAddress"

jupyter.pem: # self-sigend ssl/https certificate
	openssl req -x509 -out $@ -keyout $@ \
	        -nodes -days 365 -newkey rsa:2048 \
		-subj "/O=${USER}/OU=jupyter/CN=localhost"

pem.fingerprint: jupyter.pem
	openssl x509 -subject -fingerprint -serial -dates \
	    -noout -in $<

.PHONY: pem.fingerprint
